version: '3.0'

services:

  nodejs:
    build:
      dockerfile: ./.docker/nodejs/Dockerfile
      context: ./
    working_dir: /app/
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - ${WS_PORT}:${WS_PORT}
    volumes:
      - ./app/src:/app/src/
    depends_on:
      - postgres

  postgres:
    build: ./.docker/postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.docker-data/postgres/data:/var/lib/postgresql/data
